obstacle_detector:
  ros__parameters:
    obstacle_color_range:
      min:
        h: 0
        s: 125
        v: 125
      max:
        h: 10
        s: 255
        v: 255
    map_resolution: 100.0  # pixels per meter
    map_width: 100  # pixels
    map_height: 50   # pixels
